[package]
name = "coding_club"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "coding_club"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.16.1"
num-traits = "0.2.19"
pyo3 = "0.23.3"
